[2024-10-23T11:39:38.762+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-23T11:39:38.779+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T11:39:29.647823+00:00 [queued]>
[2024-10-23T11:39:38.791+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test.run_selenium_task manual__2024-10-23T11:39:29.647823+00:00 [queued]>
[2024-10-23T11:39:38.791+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-23T11:39:38.823+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-23 11:39:29.647823+00:00
[2024-10-23T11:39:38.829+0000] {standard_task_runner.py:72} INFO - Started process 25641 to run task
[2024-10-23T11:39:38.836+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test', 'run_selenium_task', 'manual__2024-10-23T11:39:29.647823+00:00', '--job-id', '855', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpkq0vbynx']
[2024-10-23T11:39:38.838+0000] {standard_task_runner.py:105} INFO - Job 855: Subtask run_selenium_task
[2024-10-23T11:39:38.899+0000] {task_command.py:467} INFO - Running <TaskInstance: test.run_selenium_task manual__2024-10-23T11:39:29.647823+00:00 [running]> on host 60bbe790d101
[2024-10-23T11:39:39.012+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-23T11:39:29.647823+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-23T11:39:29.647823+00:00'
[2024-10-23T11:39:39.013+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-23T11:39:39.051+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-23T11:39:39.710+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T11:39:39.869+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-23T11:39:40.013+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver-linux64/chromedriver] found in cache
[2024-10-23T11:40:08.277+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 279, in selenium_scraper
    driver.find_element(By.XPATH, f"//*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='{url}']]").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"Unable to locate an element with the xpath expression //*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']] because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']]' is not a valid XPath expression."}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
#0 0x563f8481d10a <unknown>
#1 0x563f84338460 <unknown>
#2 0x563f8433e193 <unknown>
#3 0x563f8433fe45 <unknown>
#4 0x563f8433fecc <unknown>
#5 0x563f84384bf5 <unknown>
#6 0x563f84385221 <unknown>
#7 0x563f843ca5d4 <unknown>
#8 0x563f843a903d <unknown>
#9 0x563f843c7af6 <unknown>
#10 0x563f843a8db3 <unknown>
#11 0x563f84377c10 <unknown>
#12 0x563f84378bee <unknown>
#13 0x563f847e939b <unknown>
#14 0x563f847ed338 <unknown>
#15 0x563f847d6ebc <unknown>
#16 0x563f847edeb7 <unknown>
#17 0x563f847bc10f <unknown>
#18 0x563f8480b828 <unknown>
#19 0x563f8480b9f0 <unknown>
#20 0x563f8481bf86 <unknown>
#21 0x7fce4234d144 <unknown>

[2024-10-23T11:40:08.352+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test, task_id=run_selenium_task, run_id=manual__2024-10-23T11:39:29.647823+00:00, execution_date=20241023T113929, start_date=20241023T113938, end_date=20241023T114008
[2024-10-23T11:40:08.410+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-23T11:40:08.411+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 855 for task run_selenium_task (Message: invalid selector
from javascript error: {"status":32,"value":"Unable to locate an element with the xpath expression //*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']] because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']]' is not a valid XPath expression."}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
#0 0x563f8481d10a <unknown>
#1 0x563f84338460 <unknown>
#2 0x563f8433e193 <unknown>
#3 0x563f8433fe45 <unknown>
#4 0x563f8433fecc <unknown>
#5 0x563f84384bf5 <unknown>
#6 0x563f84385221 <unknown>
#7 0x563f843ca5d4 <unknown>
#8 0x563f843a903d <unknown>
#9 0x563f843c7af6 <unknown>
#10 0x563f843a8db3 <unknown>
#11 0x563f84377c10 <unknown>
#12 0x563f84378bee <unknown>
#13 0x563f847e939b <unknown>
#14 0x563f847ed338 <unknown>
#15 0x563f847d6ebc <unknown>
#16 0x563f847edeb7 <unknown>
#17 0x563f847bc10f <unknown>
#18 0x563f8480b828 <unknown>
#19 0x563f8480b9f0 <unknown>
#20 0x563f8481bf86 <unknown>
#21 0x7fce4234d144 <unknown>
; 25641)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 279, in selenium_scraper
    driver.find_element(By.XPATH, f"//*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='{url}']]").click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSelectorException: Message: invalid selector
from javascript error: {"status":32,"value":"Unable to locate an element with the xpath expression //*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']] because of the following error:\nSyntaxError: Failed to execute 'evaluate' on 'Document': The string '//*[@id='rso']/div[1]/div/div/div/div/div/div/div/div[1]/div/span/a[@href='https://www.dcard.tw/f/tech_job']]' is not a valid XPath expression."}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#invalid-selector-exception
Stacktrace:
#0 0x563f8481d10a <unknown>
#1 0x563f84338460 <unknown>
#2 0x563f8433e193 <unknown>
#3 0x563f8433fe45 <unknown>
#4 0x563f8433fecc <unknown>
#5 0x563f84384bf5 <unknown>
#6 0x563f84385221 <unknown>
#7 0x563f843ca5d4 <unknown>
#8 0x563f843a903d <unknown>
#9 0x563f843c7af6 <unknown>
#10 0x563f843a8db3 <unknown>
#11 0x563f84377c10 <unknown>
#12 0x563f84378bee <unknown>
#13 0x563f847e939b <unknown>
#14 0x563f847ed338 <unknown>
#15 0x563f847d6ebc <unknown>
#16 0x563f847edeb7 <unknown>
#17 0x563f847bc10f <unknown>
#18 0x563f8480b828 <unknown>
#19 0x563f8480b9f0 <unknown>
#20 0x563f8481bf86 <unknown>
#21 0x7fce4234d144 <unknown>

[2024-10-23T11:40:08.458+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-23T11:40:08.474+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-23T11:40:08.475+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
