[2024-10-24T10:55:57.043+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-10-24T10:55:57.055+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:55:51.154507+00:00 [queued]>
[2024-10-24T10:55:57.063+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test3.run_selenium_task manual__2024-10-24T10:55:51.154507+00:00 [queued]>
[2024-10-24T10:55:57.063+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 2
[2024-10-24T10:55:57.082+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): run_selenium_task> on 2024-10-24 10:55:51.154507+00:00
[2024-10-24T10:55:57.088+0000] {standard_task_runner.py:72} INFO - Started process 12050 to run task
[2024-10-24T10:55:57.092+0000] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'test3', 'run_selenium_task', 'manual__2024-10-24T10:55:51.154507+00:00', '--job-id', '914', '--raw', '--subdir', 'DAGS_FOLDER/dcard_dag.py', '--cfg-path', '/tmp/tmpitsvj9n7']
[2024-10-24T10:55:57.095+0000] {standard_task_runner.py:105} INFO - Job 914: Subtask run_selenium_task
[2024-10-24T10:55:57.142+0000] {task_command.py:467} INFO - Running <TaskInstance: test3.run_selenium_task manual__2024-10-24T10:55:51.154507+00:00 [running]> on host 60bbe790d101
[2024-10-24T10:55:57.230+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='test3' AIRFLOW_CTX_TASK_ID='run_selenium_task' AIRFLOW_CTX_EXECUTION_DATE='2024-10-24T10:55:51.154507+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-10-24T10:55:51.154507+00:00'
[2024-10-24T10:55:57.231+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-10-24T10:55:57.255+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:55:57.378+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:55:57.506+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:55:57.634+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:56:20.012+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2024-10-24T10:56:20.131+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:56:20.258+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2024-10-24T10:56:20.384+0000] {logger.py:11} INFO - Driver [/home/airflow/.wdm/drivers/chromedriver/linux64/130.0.6723.69/chromedriver] found in cache
[2024-10-24T10:56:44.653+0000] {taskinstance.py:3310} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 141, in selenium_scraper
    driver1.find_element(By.CLASS_NAME, 'mfgatba').click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".mfgatba"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f914e4610a <unknown>
#1 0x55f914961460 <unknown>
#2 0x55f9149adf96 <unknown>
#3 0x55f9149ae221 <unknown>
#4 0x55f9149f35d4 <unknown>
#5 0x55f9149d203d <unknown>
#6 0x55f9149f0af6 <unknown>
#7 0x55f9149d1db3 <unknown>
#8 0x55f9149a0c10 <unknown>
#9 0x55f9149a1bee <unknown>
#10 0x55f914e1239b <unknown>
#11 0x55f914e16338 <unknown>
#12 0x55f914dffebc <unknown>
#13 0x55f914e16eb7 <unknown>
#14 0x55f914de510f <unknown>
#15 0x55f914e34828 <unknown>
#16 0x55f914e349f0 <unknown>
#17 0x55f914e44f86 <unknown>
#18 0x7f0f03582144 <unknown>

[2024-10-24T10:56:44.665+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=test3, task_id=run_selenium_task, run_id=manual__2024-10-24T10:55:51.154507+00:00, execution_date=20241024T105551, start_date=20241024T105557, end_date=20241024T105644
[2024-10-24T10:56:44.681+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-10-24T10:56:44.682+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 914 for task run_selenium_task (Message: no such element: Unable to locate element: {"method":"css selector","selector":".mfgatba"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f914e4610a <unknown>
#1 0x55f914961460 <unknown>
#2 0x55f9149adf96 <unknown>
#3 0x55f9149ae221 <unknown>
#4 0x55f9149f35d4 <unknown>
#5 0x55f9149d203d <unknown>
#6 0x55f9149f0af6 <unknown>
#7 0x55f9149d1db3 <unknown>
#8 0x55f9149a0c10 <unknown>
#9 0x55f9149a1bee <unknown>
#10 0x55f914e1239b <unknown>
#11 0x55f914e16338 <unknown>
#12 0x55f914dffebc <unknown>
#13 0x55f914e16eb7 <unknown>
#14 0x55f914de510f <unknown>
#15 0x55f914e34828 <unknown>
#16 0x55f914e349f0 <unknown>
#17 0x55f914e44f86 <unknown>
#18 0x7f0f03582144 <unknown>
; 12050)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 115, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3004, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3158, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3182, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 406, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/dcard_dag.py", line 141, in selenium_scraper
    driver1.find_element(By.CLASS_NAME, 'mfgatba').click()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":".mfgatba"}
  (Session info: chrome=130.0.6723.58); For documentation on this error, please visit: https://www.selenium.dev/documentation/webdriver/troubleshooting/errors#no-such-element-exception
Stacktrace:
#0 0x55f914e4610a <unknown>
#1 0x55f914961460 <unknown>
#2 0x55f9149adf96 <unknown>
#3 0x55f9149ae221 <unknown>
#4 0x55f9149f35d4 <unknown>
#5 0x55f9149d203d <unknown>
#6 0x55f9149f0af6 <unknown>
#7 0x55f9149d1db3 <unknown>
#8 0x55f9149a0c10 <unknown>
#9 0x55f9149a1bee <unknown>
#10 0x55f914e1239b <unknown>
#11 0x55f914e16338 <unknown>
#12 0x55f914dffebc <unknown>
#13 0x55f914e16eb7 <unknown>
#14 0x55f914de510f <unknown>
#15 0x55f914e34828 <unknown>
#16 0x55f914e349f0 <unknown>
#17 0x55f914e44f86 <unknown>
#18 0x7f0f03582144 <unknown>

[2024-10-24T10:56:44.731+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-10-24T10:56:44.744+0000] {taskinstance.py:3900} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-10-24T10:56:44.745+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
