2024-10-22 04:40:16.174 [info] Experiment 'pythonRecommendTensorboardExt' is active
2024-10-22 04:40:16.174 [info] Experiment 'pythonTerminalEnvVarActivation' is active
2024-10-22 04:40:16.175 [info] Experiment 'pythonTestAdapter' is active
2024-10-22 04:40:16.175 [warning] Dir "/home/jojoforjob/.pixi/envs" is not watchable (directory does not exist)
2024-10-22 04:40:16.175 [warning] Dir "/home/.pixi/envs" is not watchable (directory does not exist)
2024-10-22 04:40:16.175 [info] Default formatter is set to null for workspace /home/jojoforjob
2024-10-22 04:40:16.175 [info] Default formatter is set to null for workspace /home
2024-10-22 04:40:16.176 [info] Not enabling terminal env var experiment in multiroot remote workspaces
2024-10-22 04:40:16.176 [info] Starting Environment refresh
2024-10-22 04:40:16.176 [info] Starting Environment refresh
2024-10-22 04:40:16.176 [info] > pixi --version
2024-10-22 04:40:16.176 [info] > hatch env show --json
2024-10-22 04:40:16.177 [info] cwd: ~
2024-10-22 04:40:16.177 [info] > hatch env show --json
2024-10-22 04:40:16.177 [info] cwd: /home
2024-10-22 04:40:16.177 [warning] Failed to check if /usr/local/bin/python3 is an executable [Error: ENOENT: no such file or directory, lstat '/usr/local/bin/python3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/bin/python3'
}
2024-10-22 04:40:16.209 [info] Starting Environment refresh
2024-10-22 04:40:16.279 [error] readdir() failed for "/home/ubuntu/.ssh" (Error: EACCES: permission denied, scandir '/home/ubuntu/.ssh')
2024-10-22 04:40:16.280 [error] readdir() failed for "/home/ubuntu/.ssh" (Error: EACCES: permission denied, scandir '/home/ubuntu/.ssh')
2024-10-22 04:40:16.311 [info] > /usr/local/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py
2024-10-22 04:40:16.327 [info] Environments refresh paths discovered: 1008 milliseconds
2024-10-22 04:40:16.328 [info] Environments refresh paths discovered: 1008 milliseconds
2024-10-22 04:40:16.331 [error] readdir() failed for "/home/ubuntu/.ssh" (Error: EACCES: permission denied, scandir '/home/ubuntu/.ssh')
2024-10-22 04:40:16.337 [error] [Error: Command failed: /usr/local/bin/python3 -I /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: /usr/local/bin/python3: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:339:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/usr/local/bin/python3 -I /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py'
}
2024-10-22 04:40:16.353 [info] Environments refresh paths discovered: 145 milliseconds
2024-10-22 04:40:18.342 [info] > /usr/local/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py
2024-10-22 04:40:18.345 [error] [Error: Command failed: /usr/local/bin/python3 -I /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py
/bin/sh: 1: /usr/local/bin/python3: not found

	at genericNodeError (node:internal/errors:984:15)
	at wrappedFn (node:internal/errors:538:14)
	at ChildProcess.exithandler (node:child_process:422:12)
	at ChildProcess.emit (node:events:531:35)
	at maybeClose (node:internal/child_process:1105:16)
	at Socket.<anonymous> (node:internal/child_process:457:11)
	at Socket.emit (node:events:519:28)
	at Pipe.<anonymous> (node:net:339:12)] {
  code: 127,
  killed: false,
  signal: null,
  cmd: '/usr/local/bin/python3 -I /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py /home/jojoforjob/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py'
}
2024-10-22 04:40:18.345 [info] Environments refresh finished (event): 3026 milliseconds
2024-10-22 04:40:18.346 [info] Environments refresh finished (event): 3025 milliseconds
2024-10-22 04:40:18.346 [info] Environments refresh finished (event): 2137 milliseconds
2024-10-22 04:40:18.349 [info] Environment refresh took 3032 milliseconds
2024-10-22 04:40:18.350 [info] Environment refresh took 3030 milliseconds
2024-10-22 04:40:18.350 [info] Environment refresh took 2142 milliseconds
2024-10-22 04:40:18.351 [warning] Failed to check if /usr/local/bin/python3 is an executable [Error: ENOENT: no such file or directory, lstat '/usr/local/bin/python3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/bin/python3'
}
2024-10-22 04:40:18.355 [info] > pyenv which python
2024-10-22 04:40:18.355 [info] cwd: ~
2024-10-22 04:40:18.411 [info] Not enabling terminal env var experiment in multiroot remote workspaces
2024-10-22 04:40:18.529 [info] > /usr/bin/python3 -I ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/get_output_via_markers.py ~/.vscode-server/extensions/ms-python.python-2024.16.1-linux-x64/python_files/interpreterInfo.py
2024-10-22 04:40:18.898 [info] Not enabling terminal env var experiment in multiroot remote workspaces
2024-10-22 04:40:19.322 [info] Starting Pylance language server.
2024-10-22 04:40:19.358 [warning] Failed to check if /usr/local/bin/python3 is an executable [Error: ENOENT: no such file or directory, lstat '/usr/local/bin/python3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/bin/python3'
}
2024-10-22 04:40:19.433 [warning] Failed to check if /usr/local/bin/python3 is an executable [Error: ENOENT: no such file or directory, lstat '/usr/local/bin/python3'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'lstat',
  path: '/usr/local/bin/python3'
}
2024-10-22 04:40:35.382 [info] Discover tests for workspace name: jojoforjob - uri: /home/jojoforjob/dags/1.py
2024-10-22 04:42:49.853 [info] Discover tests for workspace name: jojoforjob - uri: /home/jojoforjob/dags/1.py
2024-10-22 04:42:50.939 [info] Discover tests for workspace name: jojoforjob - uri: /home/jojoforjob/dags/1.py
2024-10-22 04:42:52.240 [info] Discover tests for workspace name: jojoforjob - uri: /home/jojoforjob/dags/1.py
